// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PseudonymSystemCA service

type PseudonymSystemCAClient interface {
	GenerateCertificate(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystemCA_GenerateCertificateClient, error)
	GenerateCertificate_EC(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystemCA_GenerateCertificate_ECClient, error)
}

type pseudonymSystemCAClient struct {
	cc *grpc.ClientConn
}

func NewPseudonymSystemCAClient(cc *grpc.ClientConn) PseudonymSystemCAClient {
	return &pseudonymSystemCAClient{cc}
}

func (c *pseudonymSystemCAClient) GenerateCertificate(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystemCA_GenerateCertificateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PseudonymSystemCA_serviceDesc.Streams[0], c.cc, "/proto.PseudonymSystemCA/GenerateCertificate", opts...)
	if err != nil {
		return nil, err
	}
	x := &pseudonymSystemCAGenerateCertificateClient{stream}
	return x, nil
}

type PseudonymSystemCA_GenerateCertificateClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type pseudonymSystemCAGenerateCertificateClient struct {
	grpc.ClientStream
}

func (x *pseudonymSystemCAGenerateCertificateClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pseudonymSystemCAGenerateCertificateClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pseudonymSystemCAClient) GenerateCertificate_EC(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystemCA_GenerateCertificate_ECClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PseudonymSystemCA_serviceDesc.Streams[1], c.cc, "/proto.PseudonymSystemCA/GenerateCertificate_EC", opts...)
	if err != nil {
		return nil, err
	}
	x := &pseudonymSystemCAGenerateCertificate_ECClient{stream}
	return x, nil
}

type PseudonymSystemCA_GenerateCertificate_ECClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type pseudonymSystemCAGenerateCertificate_ECClient struct {
	grpc.ClientStream
}

func (x *pseudonymSystemCAGenerateCertificate_ECClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pseudonymSystemCAGenerateCertificate_ECClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PseudonymSystemCA service

type PseudonymSystemCAServer interface {
	GenerateCertificate(PseudonymSystemCA_GenerateCertificateServer) error
	GenerateCertificate_EC(PseudonymSystemCA_GenerateCertificate_ECServer) error
}

func RegisterPseudonymSystemCAServer(s *grpc.Server, srv PseudonymSystemCAServer) {
	s.RegisterService(&_PseudonymSystemCA_serviceDesc, srv)
}

func _PseudonymSystemCA_GenerateCertificate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PseudonymSystemCAServer).GenerateCertificate(&pseudonymSystemCAGenerateCertificateServer{stream})
}

type PseudonymSystemCA_GenerateCertificateServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type pseudonymSystemCAGenerateCertificateServer struct {
	grpc.ServerStream
}

func (x *pseudonymSystemCAGenerateCertificateServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pseudonymSystemCAGenerateCertificateServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PseudonymSystemCA_GenerateCertificate_EC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PseudonymSystemCAServer).GenerateCertificate_EC(&pseudonymSystemCAGenerateCertificate_ECServer{stream})
}

type PseudonymSystemCA_GenerateCertificate_ECServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type pseudonymSystemCAGenerateCertificate_ECServer struct {
	grpc.ServerStream
}

func (x *pseudonymSystemCAGenerateCertificate_ECServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pseudonymSystemCAGenerateCertificate_ECServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PseudonymSystemCA_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PseudonymSystemCA",
	HandlerType: (*PseudonymSystemCAServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateCertificate",
			Handler:       _PseudonymSystemCA_GenerateCertificate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GenerateCertificate_EC",
			Handler:       _PseudonymSystemCA_GenerateCertificate_EC_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services.proto",
}

// Client API for PseudonymSystem service

type PseudonymSystemClient interface {
	GenerateNym(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystem_GenerateNymClient, error)
	GenerateNym_EC(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystem_GenerateNym_ECClient, error)
	ObtainCredential(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystem_ObtainCredentialClient, error)
	ObtainCredential_EC(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystem_ObtainCredential_ECClient, error)
	TransferCredential(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystem_TransferCredentialClient, error)
	TransferCredential_EC(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystem_TransferCredential_ECClient, error)
}

type pseudonymSystemClient struct {
	cc *grpc.ClientConn
}

func NewPseudonymSystemClient(cc *grpc.ClientConn) PseudonymSystemClient {
	return &pseudonymSystemClient{cc}
}

func (c *pseudonymSystemClient) GenerateNym(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystem_GenerateNymClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PseudonymSystem_serviceDesc.Streams[0], c.cc, "/proto.PseudonymSystem/GenerateNym", opts...)
	if err != nil {
		return nil, err
	}
	x := &pseudonymSystemGenerateNymClient{stream}
	return x, nil
}

type PseudonymSystem_GenerateNymClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type pseudonymSystemGenerateNymClient struct {
	grpc.ClientStream
}

func (x *pseudonymSystemGenerateNymClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pseudonymSystemGenerateNymClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pseudonymSystemClient) GenerateNym_EC(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystem_GenerateNym_ECClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PseudonymSystem_serviceDesc.Streams[1], c.cc, "/proto.PseudonymSystem/GenerateNym_EC", opts...)
	if err != nil {
		return nil, err
	}
	x := &pseudonymSystemGenerateNym_ECClient{stream}
	return x, nil
}

type PseudonymSystem_GenerateNym_ECClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type pseudonymSystemGenerateNym_ECClient struct {
	grpc.ClientStream
}

func (x *pseudonymSystemGenerateNym_ECClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pseudonymSystemGenerateNym_ECClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pseudonymSystemClient) ObtainCredential(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystem_ObtainCredentialClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PseudonymSystem_serviceDesc.Streams[2], c.cc, "/proto.PseudonymSystem/ObtainCredential", opts...)
	if err != nil {
		return nil, err
	}
	x := &pseudonymSystemObtainCredentialClient{stream}
	return x, nil
}

type PseudonymSystem_ObtainCredentialClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type pseudonymSystemObtainCredentialClient struct {
	grpc.ClientStream
}

func (x *pseudonymSystemObtainCredentialClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pseudonymSystemObtainCredentialClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pseudonymSystemClient) ObtainCredential_EC(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystem_ObtainCredential_ECClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PseudonymSystem_serviceDesc.Streams[3], c.cc, "/proto.PseudonymSystem/ObtainCredential_EC", opts...)
	if err != nil {
		return nil, err
	}
	x := &pseudonymSystemObtainCredential_ECClient{stream}
	return x, nil
}

type PseudonymSystem_ObtainCredential_ECClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type pseudonymSystemObtainCredential_ECClient struct {
	grpc.ClientStream
}

func (x *pseudonymSystemObtainCredential_ECClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pseudonymSystemObtainCredential_ECClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pseudonymSystemClient) TransferCredential(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystem_TransferCredentialClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PseudonymSystem_serviceDesc.Streams[4], c.cc, "/proto.PseudonymSystem/TransferCredential", opts...)
	if err != nil {
		return nil, err
	}
	x := &pseudonymSystemTransferCredentialClient{stream}
	return x, nil
}

type PseudonymSystem_TransferCredentialClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type pseudonymSystemTransferCredentialClient struct {
	grpc.ClientStream
}

func (x *pseudonymSystemTransferCredentialClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pseudonymSystemTransferCredentialClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pseudonymSystemClient) TransferCredential_EC(ctx context.Context, opts ...grpc.CallOption) (PseudonymSystem_TransferCredential_ECClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PseudonymSystem_serviceDesc.Streams[5], c.cc, "/proto.PseudonymSystem/TransferCredential_EC", opts...)
	if err != nil {
		return nil, err
	}
	x := &pseudonymSystemTransferCredential_ECClient{stream}
	return x, nil
}

type PseudonymSystem_TransferCredential_ECClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type pseudonymSystemTransferCredential_ECClient struct {
	grpc.ClientStream
}

func (x *pseudonymSystemTransferCredential_ECClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pseudonymSystemTransferCredential_ECClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PseudonymSystem service

type PseudonymSystemServer interface {
	GenerateNym(PseudonymSystem_GenerateNymServer) error
	GenerateNym_EC(PseudonymSystem_GenerateNym_ECServer) error
	ObtainCredential(PseudonymSystem_ObtainCredentialServer) error
	ObtainCredential_EC(PseudonymSystem_ObtainCredential_ECServer) error
	TransferCredential(PseudonymSystem_TransferCredentialServer) error
	TransferCredential_EC(PseudonymSystem_TransferCredential_ECServer) error
}

func RegisterPseudonymSystemServer(s *grpc.Server, srv PseudonymSystemServer) {
	s.RegisterService(&_PseudonymSystem_serviceDesc, srv)
}

func _PseudonymSystem_GenerateNym_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PseudonymSystemServer).GenerateNym(&pseudonymSystemGenerateNymServer{stream})
}

type PseudonymSystem_GenerateNymServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type pseudonymSystemGenerateNymServer struct {
	grpc.ServerStream
}

func (x *pseudonymSystemGenerateNymServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pseudonymSystemGenerateNymServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PseudonymSystem_GenerateNym_EC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PseudonymSystemServer).GenerateNym_EC(&pseudonymSystemGenerateNym_ECServer{stream})
}

type PseudonymSystem_GenerateNym_ECServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type pseudonymSystemGenerateNym_ECServer struct {
	grpc.ServerStream
}

func (x *pseudonymSystemGenerateNym_ECServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pseudonymSystemGenerateNym_ECServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PseudonymSystem_ObtainCredential_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PseudonymSystemServer).ObtainCredential(&pseudonymSystemObtainCredentialServer{stream})
}

type PseudonymSystem_ObtainCredentialServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type pseudonymSystemObtainCredentialServer struct {
	grpc.ServerStream
}

func (x *pseudonymSystemObtainCredentialServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pseudonymSystemObtainCredentialServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PseudonymSystem_ObtainCredential_EC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PseudonymSystemServer).ObtainCredential_EC(&pseudonymSystemObtainCredential_ECServer{stream})
}

type PseudonymSystem_ObtainCredential_ECServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type pseudonymSystemObtainCredential_ECServer struct {
	grpc.ServerStream
}

func (x *pseudonymSystemObtainCredential_ECServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pseudonymSystemObtainCredential_ECServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PseudonymSystem_TransferCredential_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PseudonymSystemServer).TransferCredential(&pseudonymSystemTransferCredentialServer{stream})
}

type PseudonymSystem_TransferCredentialServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type pseudonymSystemTransferCredentialServer struct {
	grpc.ServerStream
}

func (x *pseudonymSystemTransferCredentialServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pseudonymSystemTransferCredentialServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PseudonymSystem_TransferCredential_EC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PseudonymSystemServer).TransferCredential_EC(&pseudonymSystemTransferCredential_ECServer{stream})
}

type PseudonymSystem_TransferCredential_ECServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type pseudonymSystemTransferCredential_ECServer struct {
	grpc.ServerStream
}

func (x *pseudonymSystemTransferCredential_ECServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pseudonymSystemTransferCredential_ECServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PseudonymSystem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PseudonymSystem",
	HandlerType: (*PseudonymSystemServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateNym",
			Handler:       _PseudonymSystem_GenerateNym_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GenerateNym_EC",
			Handler:       _PseudonymSystem_GenerateNym_EC_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ObtainCredential",
			Handler:       _PseudonymSystem_ObtainCredential_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ObtainCredential_EC",
			Handler:       _PseudonymSystem_ObtainCredential_EC_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "TransferCredential",
			Handler:       _PseudonymSystem_TransferCredential_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "TransferCredential_EC",
			Handler:       _PseudonymSystem_TransferCredential_EC_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services.proto",
}

// Client API for CL service

type CLClient interface {
	GetCredentialIssueNonce(ctx context.Context, opts ...grpc.CallOption) (CL_GetCredentialIssueNonceClient, error)
}

type cLClient struct {
	cc *grpc.ClientConn
}

func NewCLClient(cc *grpc.ClientConn) CLClient {
	return &cLClient{cc}
}

func (c *cLClient) GetCredentialIssueNonce(ctx context.Context, opts ...grpc.CallOption) (CL_GetCredentialIssueNonceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CL_serviceDesc.Streams[0], c.cc, "/proto.CL/GetCredentialIssueNonce", opts...)
	if err != nil {
		return nil, err
	}
	x := &cLGetCredentialIssueNonceClient{stream}
	return x, nil
}

type CL_GetCredentialIssueNonceClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type cLGetCredentialIssueNonceClient struct {
	grpc.ClientStream
}

func (x *cLGetCredentialIssueNonceClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cLGetCredentialIssueNonceClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CL service

type CLServer interface {
	GetCredentialIssueNonce(CL_GetCredentialIssueNonceServer) error
}

func RegisterCLServer(s *grpc.Server, srv CLServer) {
	s.RegisterService(&_CL_serviceDesc, srv)
}

func _CL_GetCredentialIssueNonce_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CLServer).GetCredentialIssueNonce(&cLGetCredentialIssueNonceServer{stream})
}

type CL_GetCredentialIssueNonceServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type cLGetCredentialIssueNonceServer struct {
	grpc.ServerStream
}

func (x *cLGetCredentialIssueNonceServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cLGetCredentialIssueNonceServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CL_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CL",
	HandlerType: (*CLServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCredentialIssueNonce",
			Handler:       _CL_GetCredentialIssueNonce_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services.proto",
}

// Client API for Info service

type InfoClient interface {
	GetServiceInfo(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*ServiceInfo, error)
}

type infoClient struct {
	cc *grpc.ClientConn
}

func NewInfoClient(cc *grpc.ClientConn) InfoClient {
	return &infoClient{cc}
}

func (c *infoClient) GetServiceInfo(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*ServiceInfo, error) {
	out := new(ServiceInfo)
	err := grpc.Invoke(ctx, "/proto.Info/GetServiceInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Info service

type InfoServer interface {
	GetServiceInfo(context.Context, *google_protobuf.Empty) (*ServiceInfo, error)
}

func RegisterInfoServer(s *grpc.Server, srv InfoServer) {
	s.RegisterService(&_Info_serviceDesc, srv)
}

func _Info_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Info/GetServiceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).GetServiceInfo(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Info_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Info",
	HandlerType: (*InfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceInfo",
			Handler:    _Info_GetServiceInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}

func init() { proto1.RegisterFile("services.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdb, 0xa2, 0x1e, 0x46, 0x88, 0x3a, 0xc5, 0x0a, 0xf1, 0xd6, 0x93, 0xa7, 0x54, 0x52,
	0x10, 0xb1, 0x58, 0x91, 0x10, 0x4b, 0x41, 0xab, 0x50, 0xef, 0xb2, 0x49, 0x27, 0x21, 0xd0, 0xec,
	0x96, 0xdd, 0x89, 0x90, 0xb7, 0xf0, 0x51, 0x7d, 0x04, 0x69, 0x62, 0xb0, 0x44, 0x0f, 0xeb, 0x69,
	0x99, 0xd9, 0xfd, 0xe6, 0xff, 0x99, 0xfd, 0xc1, 0x31, 0xa4, 0xdf, 0xb3, 0x98, 0x8c, 0xb7, 0xd1,
	0x8a, 0x15, 0xee, 0x57, 0x87, 0xeb, 0xe4, 0x64, 0x8c, 0x48, 0x9b, 0xb6, 0x7b, 0x9e, 0x2a, 0x95,
	0xae, 0x69, 0x54, 0x55, 0x51, 0x91, 0x8c, 0x28, 0xdf, 0x70, 0x59, 0x5f, 0xfa, 0x1f, 0x5d, 0x38,
	0x79, 0x31, 0x54, 0xac, 0x94, 0x2c, 0xf3, 0x65, 0x69, 0x98, 0xf2, 0xe0, 0x1e, 0x27, 0xd0, 0x9f,
	0x91, 0x24, 0x2d, 0x98, 0x02, 0xd2, 0x9c, 0x25, 0x59, 0x2c, 0x98, 0xd0, 0xa9, 0x21, 0xef, 0xa9,
	0x16, 0x70, 0x5b, 0xf5, 0xb0, 0x73, 0xd1, 0xbd, 0xec, 0xe2, 0x14, 0x06, 0x7f, 0xc0, 0x6f, 0x61,
	0x60, 0xc7, 0xfb, 0x9f, 0x3d, 0x38, 0x6a, 0x59, 0xc2, 0x31, 0x1c, 0x36, 0x33, 0x17, 0x65, 0x6e,
	0x69, 0xe4, 0x0a, 0x9c, 0x1d, 0xc8, 0xda, 0x00, 0x5e, 0xc3, 0xf1, 0x73, 0xc4, 0x22, 0x93, 0x81,
	0xa6, 0x15, 0x49, 0xce, 0xc4, 0xda, 0x92, 0x9c, 0x40, 0xbf, 0x4d, 0xda, 0xcb, 0xde, 0x00, 0xbe,
	0x6a, 0x21, 0x4d, 0x42, 0xfa, 0xdf, 0xc2, 0xb7, 0x70, 0xfa, 0x9b, 0xb5, 0x5f, 0x79, 0x08, 0xbd,
	0xe0, 0x11, 0xef, 0xe0, 0x6c, 0x46, 0xfc, 0xc3, 0xcf, 0x8d, 0x29, 0x68, 0xa1, 0x64, 0x6c, 0xf9,
	0xf3, 0xfe, 0x03, 0xec, 0xcd, 0x65, 0xa2, 0x70, 0xba, 0x5d, 0x3c, 0x2f, 0xeb, 0x74, 0x56, 0x9d,
	0x81, 0x57, 0x87, 0xd0, 0x6b, 0x42, 0xe8, 0x85, 0xdb, 0x10, 0xba, 0xf8, 0x3d, 0x67, 0xe7, 0xed,
	0xb0, 0x13, 0x1d, 0x54, 0xcd, 0xf1, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xef, 0x1a, 0xb6,
	0xe1, 0x02, 0x00, 0x00,
}
